name: React CI
run-name: ${{ github.actor }} is pushing and deploying

on: 
  push:
    branches:
      - main
  # pull_request:
  #   types:
  #     - closed
  #   branches:
  #     - main

jobs:
  # build:
  #   name: Build and unit test
  #   runs-on: ubuntu-latest
  #   steps:
  #     - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
  #     - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
  #     - uses: actions/checkout@v4
  #     - uses: actions/setup-node@v4
  #       with:
  #         node-version: '14'
  #     - name: Install dependencies
  #       run: npm install
  #     - name: Build the App
  #       run: npm run build --if-present
      # - run: npm test

  deploy:
    name: Firebase deploy
    # needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
      - run: npm install
      - run: npm run build
      - run: npm install -g firebase-tools
      - run: firebase deploy --token "${{ secrets.FIREBASE_DEPLOY_TOKEN }}" --non-interactive
      - run: echo "ğŸ This job's status is ${{ job.status }}."
